### ISSUE TITLE
Async demo 09: Never stops after running 14+ requests

### ISSUE THREAD

**Issue by kabua** [App-vNext/Polly-Samples#25] opened 2021-04-14 17:36 UTC
After running the demo a few times and allowing it to run for several request, 14+ times), the screen fills up with
```.Log, then retry: Cannot access a disposed object.
Object name: 'System.Net.Http.HttpClient'.
```
The exception happens on line 159.

**Comment by martincostello** [comment] 2021-04-14 17:42
Looks like when the loop ends by the `CancellationToken` being fired and the `HttpClient` is disposed of:

https://github.com/App-vNext/Polly-Samples/blob/88c3b8e8373bdefcf8012f1c09325f6de5ba2db0/PollyDemos/Async/AsyncDemo09_Wrap-Fallback-Timeout-WaitAndRetry.cs#L144

If there are any cancelled HTTP requests still pending to run, they'll try to use the now-disposed `HttpClient`, causing an `ObjectDisposedException`:

https://github.com/App-vNext/Polly-Samples/blob/88c3b8e8373bdefcf8012f1c09325f6de5ba2db0/PollyDemos/Async/AsyncDemo09_Wrap-Fallback-Timeout-WaitAndRetry.cs#L159

**Comment by kabua** [comment] 2021-04-14 23:40
Yes, that is correct. 

However, the policy is configured to handle **all exceptions** and to run **forever**, and the policyWrap.ExecuteAsync() is accepting a `cancellationToken` but which appears not to be honoring.

Also, how would I write something like, handle all exceptions except for `MyException`? Something like:
```Policy.Handle<Exception>().ButNot<MyException>()...```

Thanks.

**Comment by martincostello** [comment] 2023-09-29 10:42
@peter-csala Something to consider when you get to migrating this demo.

**Comment by peter-csala** [comment] 2023-10-12 11:42
After the V8 migration I can not reproduce the problem.

![issue25(2)](https://github.com/App-vNext/Polly-Samples/assets/57183693/0227d41f-fa4a-48a1-8812-050067e8d6cc)

@martincostello  I think we can close this if you agree.

**Comment by peter-csala** [comment] 2023-10-12 11:49
After the V8 migration I can not reproduce the problem. The application can be stopped any time.

![samples_issue_25](https://github.com/App-vNext/Polly-Samples/assets/57183693/6bdc613f-9171-4285-b1be-7de35f75697f)

@martincostello I think we can close this issue if you agree.

**Closed** 2023-10-12 11:50 UTC
