### ISSUE TITLE
Finalize (OnSuccess Action) the  WaitAndRetryAsync with a WrapAsync Policy

### ISSUE THREAD

**Issue by BartHuls** [App-vNext/Polly-Samples#20] opened 2019-07-08 13:39 UTC
I have a FallbackAsync Policy combined with a WaitAndRetryAsync Policy.
Both Policies are wrapped together with WrapAsync.
FallbackPolicy.WrapAsync(RetryPolicy). This works.

Is have a need to add some Finalizer eq. When the WaitAndRetryAsync succeeds  like the fallbackAction but in the  WaitAndRetryAsync

**Comment by reisenberger** [comment] 2019-07-09 19:25
Duplicate of https://github.com/App-vNext/Polly/issues/663

**Closed by reisenberger** 2019-07-09 19:25 UTC
